AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon-drawing-game
  
  Pokémon Drawing Game with AI recognition using AWS Bedrock

# Global configuration
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs22.x
    Architectures:
      - x86_64

# Parameters
Parameters:
  AdminEmail:
    Type: String
    Description: Email address for CloudWatch alarm notifications
    Default: admin@example.com
  
  BedrockRegion:
    Type: String
    Description: AWS region where Bedrock is available
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-west-1
      - ap-southeast-1
      - ap-northeast-1

# Resources
Resources:
  # Lambda function with Function URL
  PokemonLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Description: Pokémon drawing recognition using AWS Bedrock InvokeModel API
      Environment:
        Variables:
          BEDROCK_REGION: !Ref BedrockRegion
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowCredentials: false
          AllowHeaders:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
          AllowMethods:
            - POST
          AllowOrigins:
            - "https://d1mi77qn6jcpqo.cloudfront.net"
          MaxAge: 3600
      Role: !GetAtt LambdaExecutionRole.Arn

  # IAM role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockInvokeModelPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${BedrockRegion}::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0'

  # S3 bucket for frontend hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pokemon-drawing-game-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # Note: S3 bucket policy is managed manually via AWS CLI to avoid circular dependency
  # Use this command after deployment:
  # aws s3api put-bucket-policy --bucket <bucket-name> --policy file://bucket-policy.json

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # SNS topic for CloudWatch alarms
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: pokemon-game-alerts
      DisplayName: Pokémon Game Alerts

  # SNS subscription for email notifications
  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref AlarmTopic
      Endpoint: !Ref AdminEmail

  # CloudWatch alarm for high Lambda invocation volume
  HighInvocationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-HighInvocationVolume'
      AlarmDescription: Alert when Lambda invocations exceed 100 per day
      MetricName: Invocations
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

  # CloudWatch alarm for Bedrock cost protection
  CostProtectionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-BedrockCostProtection'
      AlarmDescription: Alert when Bedrock invocations exceed 233 per week (1000 per month equivalent)
      MetricName: Invocations
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 604800  # 7 days (maximum allowed)
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 233  # Approximately 1000 per month (1000/30*7 = 233)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

  # CloudWatch alarm for Lambda error rate
  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-LambdaErrorRate'
      AlarmDescription: Alert when Lambda error rate exceeds 10%
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 3
      DatapointsToAlarm: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

# Outputs
Outputs:
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt PokemonLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'

  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  S3BucketName:
    Description: S3 bucket name for frontend hosting
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  SNSTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub '${AWS::StackName}-SNSTopicArn'