AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon-drawing-game
  
  Pokémon Drawing Game with AI recognition using AWS Bedrock

# Global configuration
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64

# Parameters
Parameters:
  AdminEmail:
    Type: String
    Description: Email address for CloudWatch alarm notifications
    Default: admin@example.com
  
  BedrockRegion:
    Type: String
    Description: AWS region where Bedrock is available
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-west-1
      - ap-southeast-1
      - ap-northeast-1

# Resources
Resources:
  # Lambda function with Function URL
  PokemonLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Description: Pokémon drawing recognition using AWS Bedrock
      Environment:
        Variables:
          BEDROCK_REGION: !Ref BedrockRegion
          BEDROCK_AGENT_ID: !Ref PokemonBedrockAgent
          BEDROCK_AGENT_ALIAS_ID: !Ref PokemonBedrockAgentAlias
      Events:
        FunctionUrlEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: post
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowCredentials: false
          AllowHeaders:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
          AllowMethods:
            - POST
            - OPTIONS
          AllowOrigins:
            - "*"  # Will be updated with CloudFront domain after deployment
          MaxAge: 3600
      Role: !GetAtt LambdaExecutionRole.Arn

  # IAM role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAgentInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock-agent-runtime:InvokeAgent
                Resource: !Sub 'arn:aws:bedrock-agent:${BedrockRegion}:${AWS::AccountId}:agent-alias/${PokemonBedrockAgent}/${PokemonBedrockAgentAlias}'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${BedrockRegion}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'

  # Bedrock Agent for Pokémon identification
  PokemonBedrockAgent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: PokemonIdentifierAgent
      Description: AI agent that identifies Pokémon from drawings
      FoundationModel: anthropic.claude-3-haiku-20240307-v1:0
      Instruction: |
        You are a Pokémon identification expert. When given an image of a drawing, analyze it and identify which Pokémon was drawn. 
        
        Your response must be in JSON format with exactly these fields:
        {
          "pokemonName": "Name of the identified Pokémon",
          "confidenceScore": 85,
          "explanation": "Detailed explanation of why you think this is the identified Pokémon, mentioning specific visual features like shape, colors, and distinctive characteristics."
        }
        
        Rules:
        - confidenceScore must be a number between 0 and 100
        - pokemonName should be the official Pokémon name (e.g., "Pikachu", "Charizard")
        - explanation should be detailed and mention specific visual features
        - If you're unsure, still provide your best guess but with a lower confidence score
        - Only respond with the JSON object, no additional text
      AgentResourceRoleArn: !GetAtt BedrockAgentRole.Arn

  # IAM role for Bedrock Agent
  BedrockAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAgentModelInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${BedrockRegion}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'

  # Bedrock Agent Alias
  PokemonBedrockAgentAlias:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentId: !Ref PokemonBedrockAgent
      AgentAliasName: production
      Description: Production alias for Pokémon identifier agent

  # S3 bucket for frontend hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pokemon-drawing-game-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # S3 bucket policy for CloudFront access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # SNS topic for CloudWatch alarms
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: pokemon-game-alerts
      DisplayName: Pokémon Game Alerts

  # SNS subscription for email notifications
  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref AlarmTopic
      Endpoint: !Ref AdminEmail

  # CloudWatch alarm for high Lambda invocation volume
  HighInvocationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-HighInvocationVolume'
      AlarmDescription: Alert when Lambda invocations exceed 1500 per day
      MetricName: Invocations
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

  # CloudWatch alarm for Bedrock cost protection
  CostProtectionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-BedrockCostProtection'
      AlarmDescription: Alert when Bedrock invocations exceed 2000 per month
      MetricName: Invocations
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 2592000  # 30 days
      EvaluationPeriods: 1
      Threshold: 2000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

  # CloudWatch alarm for Lambda error rate
  ErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-LambdaErrorRate'
      AlarmDescription: Alert when Lambda error rate exceeds 10%
      MetricName: ErrorRate
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300  # 5 minutes
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PokemonLambda
      AlarmActions:
        - !Ref AlarmTopic

# Outputs
Outputs:
  LambdaFunctionUrl:
    Description: Lambda Function URL for the Pokémon recognition API
    Value: !GetAtt PokemonLambdaUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionUrl'

  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  S3BucketName:
    Description: S3 bucket name for frontend hosting
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  BedrockAgentId:
    Description: Bedrock Agent ID
    Value: !Ref PokemonBedrockAgent
    Export:
      Name: !Sub '${AWS::StackName}-BedrockAgentId'

  BedrockAgentAliasId:
    Description: Bedrock Agent Alias ID
    Value: !Ref PokemonBedrockAgentAlias
    Export:
      Name: !Sub '${AWS::StackName}-BedrockAgentAliasId'

  SNSTopicArn:
    Description: SNS Topic ARN for alerts
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub '${AWS::StackName}-SNSTopicArn'